# Generated by Django 3.0.2 on 2020-02-22 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmes',
            options={'verbose_name_plural': 'Filmes'},
        ),
    ]
