# Generated by Django 3.0.2 on 2020-02-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200222_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmes',
            name='receita',
            field=models.FloatField(default=0),
        ),
    ]
